# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170411_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='post',
            field=models.CharField(max_length=179),
        ),
    ]
